LIST_OF_RIGHT = [
    "Jyllands-Posten",
    "BT.dk",
    "B.T.",
    "Børsen",
    "BørsenLørdag",
    "Weekendavisen.dk",
    "JPAarhus",
    "B.dk",
    "Berlingske",
    "BørsenSøndag",
    "Jyllands-Posten",
    "Weekendavisen",
]
LIST_OF_LEFT = [
    "Information.dk(Abonnementsområde)",
    "Information.dk",
    "Information",
    "EkstraBladet",
    "Politiken",
]

LIST_OF_STOPPERS = [
    "LINEA SØGAARD-LIDELL EU-parlamentariker, Venstre.",
    " I LLU ST RATION: ",
    " Kilde: Beskæftigelsesministeriet. ,",
    " dorte.boddum@finans.dk",
    " mie.l.raatz@jp.dk ",
    " segj@information.dk",
    ". (arkivfoto)",
    " FOTO: ",
    " frederikke.traeholt@jp.dk",
    ". Ritzau.",
    "Camilla Gregersen Dansk Magisterforening.",
    " makr@information.dk",
    "MICHELLA MEIER-MORSI. , Michella Meier-Morsi og Mark Morsi med deres fem børn. Privatfoto",
    " (ARKIV)",
    " loka@berlingske.dk , ",
    " jonas.proschold@pol.dk",
    "SIDE 8-9. FOTO: ",
    " elisabet.svane@pol.dk ,",
    " ILLUSTRATION: ",
    "Kilder: EU-",
    "Kilder: Folketingets",
    "Kilde: \\ ",
    "Kilder: Danmarks Statistik, Politiken, Ritzau. ",
    " sonne@information.dk ",
    " , laura.nissen@jp.dk",
    " PR-foto",
    "Ark kivfoto: ",
    "anders.m.bruun@finans.dk Illustration: ",
    "winther@k.dk Fakta:",
    "FOTO: PER",
    "Fakta: FAKTA ",
    "Fejl og Fakta 28.10.2021:",
    "Fakta: Hvad mener du? Send ",
    " ELSE JOHANNESSEN,",
    " Fakta: BLÅ BOG ",
    "Se alle 140 underskrivere på information.dk/ deltag.",
    " (Foto: ",
    " (© COLORBOX) ",
    "hejs@berlingske.dk tbre@berlingske.dk",
    " KILDER: ",
    " information. dk/deltag ",
    " Arkivfoto: ",
    "Se klippet fra samtalen mellem Alex Vanopslagh og Søren Pind her.",
    "LÆS OGSÅ KRONIKKEN SIDE ",
    "PRIVAT",
    " Berlingske Grafik: ",
    "/ ritzau/",
    " Læs mere her. , FOLD UD ",
    "Alt mediemateriale fra Infomedia er ophavsretligt beskyttet.",
    "/Ritzau/",
    " Fold sammen Læs mere ",
    "/ritzau/",
    " Foto: ",
]

MAPPING = {
    "socialdemokratisk": "socialdemokrati",
    "sammenligning": "sammenligne",
    "regle": "regler",
    "parret": "par",
    "orlovsug": "orlov",
    "økonom": "økonomi",
    "økonomisk": "økonomi",
    "økonomii": "økonomi",
    "økonomiisk": "økonomi",
    "mødre": "mor",
    "moder": "mor",
    "mødr": "mor",
    "mødrene": "mor",
    "mødree": "mor",
    "mødree": "mor",
    "mødreene": "mor",
    "modell": "model",
    "mænds": "mand",
    "mændene": "mand",
    "kvinder": "kvinde",
    "kvinders": "kvinde",
    "kvinderne": "kvinde",
    "kvind": "kvinde",
    "kvinderr": "kvinde",
    "kvinderrelig": "kvinde",
    "kvinderrer": "kvinde",
    "kvinderererererre": "kvinde",
    "kvindererererer": "kvinde",
    "konsekvense": "konsekvens",
    "konkre": "konkret",
    "idé": "ide",
    "forvej": "forvejen",
    "forældr": "forældre",
    "famili": "familie",
    "familiee": "familie",
    "fagbevægelsen": "fagbevægelse",
    "fagbevægels": "fagbevægelse",
    "fagbevægelsenens": "fagbevægelse",
    "fars": "far",
    "fædr": "far",
    "fædrene": "far",
    "fædrenes": "far",
    "fædres": "far",
    "fader": "far",
    "farene": "far",
    "farenes": "far",
    "fares": "far",
    "barselsug": "barselsuge",
    "barsle": "barsel",
    "barslenn": "barsel",
    "barslen": "barsel",
    "barselslovgivning": "barselslov",
    "barselsorloven": "barselsorlov",
    "barselsregler": "barselsregel",
    "barselsregle": "barselsregel",
    "barselsreglerrr": "barselsregel",
    "barselsreglerr": "barselsregel",
    "barselsugeee": "barselsuge",
    "barselsugee": "barselsuge",
    "børn": "barn",
    "børnenes": "barn",
    "børns": "barn",
    "forældree": "forældre",
    "konkrett": "konkret",
    "ligestillingsminist": "ligestillingsminister",
    "ligestillingsordføre": "ligestillingsordfører",
    "fagbevægelsenenenenen": "fagbevægelse",
}